matrix:
  include:
    - language: python
      python:
        - 2.7
        - 3.4
        - 3.5
        - 3.6
      before_install:
        - sudo python setup.py install
        - cd guider
      install:
        - pip install -r requirements.txt
      script:
        - make
        - guider top -R 10 -o
        - guider draw guider.out
      after_success:
        - cd ..

    - language: node_js
      node_js:
        - 6
        - 8
      before_install:
        - cd guider-vue
      install:
        - npm install
        - npm run dev
        - npm run build
      script:
        - npm --version
      cache: npm
      after_success:
        - cd ..
